[general]
live_config_reload = true

[font]
normal = { family = "ProFontWindowsNerdFont", style = "Regular" }
size = 13.25 

[colors.primary]
background = "#000000"

[cursor]
style = { shape="Block", blinking="Always" } 
blink_interval = 500
blink_timeout = 10
